name = "chess-backend"
main = "src/index.js"
compatibility_date = "2024-09-13"

[[durable_objects.bindings]]
name = "ChessGame"
class_name = "ChessGame"

[[migrations]]
tag = "init"
new_sqlite_classes = ["ChessGame"]
